---
title: "Trends in provision of elective care in the independent sector"
author: "Alexander Lawless"
output: 
  html_document:
    theme: cerulean
    toc: TRUE
    toc_float: TRUE
    toc_collapsed: FALSE
    toc_depth: 4
    number_sections: TRUE
    code_folding: hide
---

```{r setup, include=FALSE, warnings=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings=FALSE, message=FALSE, fig.width =12, fig.height = 9)

library(tidyverse)
library(janitor)
library(scales)
library(DT)
library(patchwork)

create_dt <- function(x) {
    
    DT::datatable(
        x
        , extensions = "Buttons"
        , options = list(
            dom = "Blfrtip"
            , buttons = c("copy", "csv")
            , lengthMenu = list(
                c(10, 25, 50, -1)
                , c(10, 25, 50, "All"))))
}

# Set SU theme ####
SU_colours <- c (
  `orange`                     = grDevices::rgb(248,191,7, maxColorValue = 255),# "#f9bf07",
  `charcoal`                   = grDevices::rgb(44,40,37, maxColorValue = 255),# "#2c2825",
  `slate`                      = grDevices::rgb(104,111,115, maxColorValue = 255), # "#686f73",
  `blue`                       = grDevices::rgb(88,29,193, maxColorValue = 255), # "#5881c1",
  `red`                        = grDevices::rgb(236,101,85, maxColorValue = 255), # "#ec6555",
  #additional accent colours from word doc template
  `yellow`                     = grDevices::rgb(252,229,155, maxColorValue = 255),
  `grey`                       = grDevices::rgb(163,168,172, maxColorValue = 255),
  `white`                      = grDevices::rgb(255,255,255, maxColorValue = 255),
  #light and dark ends from colour theme in word doc
  `light orange`               = grDevices::rgb(253,242,205, maxColorValue = 255),
  `dark orange`                = grDevices::rgb(124,95,3, maxColorValue = 255),
  `light charcoal`             = grDevices::rgb(235,233,231, maxColorValue = 255),
  `dark charcoal`              = 	"#000000",#black
  `light slate`                = grDevices::rgb(224,226,227, maxColorValue = 255),
  `dark slate`                 = grDevices::rgb(51,55,57, maxColorValue = 255),
  `light blue`                 = grDevices::rgb(221,229,242, maxColorValue = 255),
  `dark blue`                  = grDevices::rgb(38,61,102, maxColorValue = 255),
  `light red`                  = grDevices::rgb(251,224,220, maxColorValue = 255),
  `dark red`                   = grDevices::rgb(144,29,16, maxColorValue = 255),
  `light yellow`               = grDevices::rgb(254,249,235, maxColorValue = 255),
  `dark yellow`                = grDevices::rgb(197,152,5, maxColorValue = 255),
  `light grey`                 = grDevices::rgb(236,237,238, maxColorValue = 255),
  `dark grey`                  = grDevices::rgb(79,84,88, maxColorValue = 255),
  `light white`                = grDevices::rgb(242,242,242, maxColorValue = 255),
  `dark white`                 = grDevices::rgb(127,127,127, maxColorValue = 255),
  `red2`                       = grDevices::rgb(215,25,28, maxColorValue = 255),
  `orange2`                    = grDevices::rgb(253,174,97, maxColorValue = 255),
  `yellow2`                    = grDevices::rgb(255,255,191, maxColorValue = 255),
  `green2`                     = grDevices::rgb(171,221,164, maxColorValue = 255),
  `blue2`                      = grDevices::rgb(43,131,186, maxColorValue = 255) #"#2b83ba"
)

SU_cols <- function(...) {
  cols <- c(...)
  
  if (is.null(cols))
    return (SU_colours)
  
  SU_colours[cols]
}

SU_palettes <- list(
  `main` = SU_cols("orange","charcoal","slate","blue","red"),
  `oranges` = SU_cols("light orange","orange","dark orange"),
  `slates` = SU_cols("light slate","slate","dark slate"),
  `mixed` = SU_cols("dark red","orange","yellow","light blue","slate"),
  `oj_coal` = SU_cols("yellow","orange","red","dark red","dark charcoal"),
  `oj_red` = SU_cols("yellow","orange","red","dark red"),
  `white_oj_coal` = SU_cols("white","yellow","orange","red","dark red","dark charcoal"),#added since shared
  `lyellow_oj_coal` = SU_cols("light yellow","orange","red","dark red","dark charcoal"),#added since shared
  `wy_oj_coal` = SU_cols("white","light yellow","yellow","orange","red","dark red","charcoal","dark charcoal"),
  `red_coal` = SU_cols("red","dark red","charcoal","dark charcoal"),
  `blue_yellow_red` = SU_cols("red2","orange2","yellow2","green2","blue2"),
  `red_yellow_blue` = SU_cols("blue2","green2","yellow2","orange2","red2")
)


SU_pal <- function(palette = "main", reverse = FALSE, ...) {
  pal <- SU_palettes[[palette]]
  
  if (reverse) pal <- rev(pal)
  
  colorRampPalette(pal, ...)
}


scale_color_SU <- function(palette = "main", discrete = TRUE, reverse = FALSE, ...) {
  pal <- SU_pal(palette = palette, reverse = reverse)
  
  if (discrete) {
    discrete_scale("colour", paste0("SU_", palette), palette = pal, ...)
  } else {
    scale_color_gradientn(colours = pal(256), ...)
  }
}

scale_fill_SU <- function(palette = "main", discrete = TRUE, reverse = FALSE, ...) {
  pal <- SU_pal(palette = palette, reverse = reverse)
  
  if (discrete) {
    discrete_scale("fill", paste0("SU_", palette), palette = pal, ...)
  } else {
    scale_fill_gradientn(colours = pal(256), ...)
  }
}  

theme_SU <-   function (base_size){
  theme_minimal(
    #base_family = "Segoe UI", 
    base_size=12
  ) %+replace% 
    theme(axis.title = element_text(size=11, face="bold",colour=SU_cols("charcoal")),
          plot.title = element_text(hjust=0,face="bold",size=12,colour=SU_cols("charcoal"),margin=margin(b=4,unit="pt")),
          plot.subtitle = element_text(hjust=0,face="italic",size=10,colour=SU_cols("charcoal"),margin=margin(b=4,unit="pt")),
          plot.caption = element_text(hjust = 0,face="italic",size=9,colour=SU_cols("slate"),margin=margin(b=4,unit="pt")),
          legend.text = element_text(size=10,colour=SU_cols("charcoal")),
          legend.title = element_text(face="bold",size=11,colour=SU_cols("charcoal"),margin=margin(b=4,unit="pt")))
}

theme_set(theme_SU())

# Read in data/functions ----
# Local/regional data 
# Look up(s)
stp_region_lookup <- 
  read_csv("STP to NHS England Region (April 2020).csv") %>% 
  clean_names()

sum_spells_function <- function(data) {
  
  data %>%  
    summarise(n_spells_IP = sum(n_spells_IP, na.rm = TRUE),
              n_spells_OP = sum(n_spells_OP, na.rm = TRUE),
              cost = sum(cost_IP, cost_OP, na.rm = TRUE)
              )
  }

wrangle_function <- function(data, var_1) {
  
  data <- 
    data %>% 
    mutate(var_1 = {{var_1}})
  
  data %>%   
    group_by(der_activity_month, var_1, type) %>% 
    sum_spells_function(.) %>% 
    group_by(der_activity_month, type, var_1) %>% 
    mutate(total_activity = sum(n_spells_IP, n_spells_OP)) %>% 
    pivot_longer(cols = c(-der_activity_month, -type, -var_1)) %>% 
    pivot_wider(id_cols = c(der_activity_month, var_1, name), 
                names_from = type,
                values_from = value
                ) %>% 
    mutate(`Independent Sector` = case_when(is.na(`Independent Sector`) ~ 0, TRUE ~ `Independent Sector`)) %>% 
    group_by(der_activity_month, var_1, name) %>% 
    mutate(prop = `Independent Sector`/ sum(`Independent Sector`, `NHS`) * 100) %>% 
    mutate(name = case_when(str_detect(name, "IP") ~ "Inpatient admissions", 
                            str_detect(name, "OP") ~ "Outpatient appointments",
                            str_detect(name, "cost") ~ "Costs",
                            TRUE ~ "All activity")) %>% 
    filter(der_activity_month > "2018-01-01" &
             der_activity_month < "2022-11-01") %>%
    filter(name != "All activity") %>% 
    ungroup() %>% 
    filter(name != "Costs")
}


graph_function <- function(data, subtitle_speciality ) {
  
  data %>% 
    ggplot(aes(x = der_activity_month, y = prop, colour = name)) +
    geom_smooth(method = "loess", span = 0.3) +
    #facet_grid(imd_quintile~ethnicity_broad) +
    scale_color_SU() +
    scale_y_continuous(labels = comma, oob = squish) +
    theme(strip.background = element_rect(fill = NA, colour = "grey"),
          strip.text = element_text(face = "bold"), 
          legend.position = "bottom",
          axis.text.x = element_text(angle = 90),
          axis.title.x = element_blank()
          ) +
    labs(y = "Independent sector proportion (%)",
         colour = "",
         title = "Independent sector proportion of activity",
         subtitle = paste0(subtitle_speciality, " elective procedures | National | 2018-22")
    )
}

# Data
stp_data <- 
  read_csv("stp_data.csv") %>% 
  left_join(stp_region_lookup, by = c("stp21nm" = "stp20nm")) %>% 
  mutate(nhser20nm = case_when(str_detect(stp21nm, "Sussex")~ "South East", TRUE ~ nhser20nm))

stp_data_ortho <-
  stp_data %>% 
  filter(speciality == "Orthopaedic")

stp_name_short_lookup <-
  tribble(
  ~stp_name, ~stp_name_short,
  
  "Bath and North East Somerset, Swindon and Wiltshire",  "Bath and North East Somerset, Swindon and Wiltshire",
  "Bedfordshire, Luton and Milton Keynes", "Bedfordshire, Luton and Milton Keynes",
  "Birmingham and Solihull", "Birmingham and Solihull",
  "Bristol, North Somerset and South Gloucestershire", "Bristol, North Somerset and South Gloucestershire",
  "Buckinghamshire, Oxfordshire and Berkshire West", "Buckinghamshire, Oxfordshire and Berkshire West",
  "Cambridgeshire and Peterborough", "Cambridgeshire and Peterborough",
  "Cheshire and Merseyside", "Cheshire and Merseyside",
  "Cornwall and the Isles of Scilly Health and Social Care Partnership", "Cornwall and the Isles of Scilly",
  "Coventry and Warwickshire", "Coventry and Warwickshire",
  "Cumbria and North East", "Cumbria and North East",
  "Devon", "Devon",
  "Dorset", "Dorset",
  "East London Health and Care Partnership", "East London",
  "Frimley Health and Care ICS", "Frimley ",
  "Gloucestershire", "Gloucestershire",
  "Greater Manchester Health and Social Care Partnership", "Greater Manchester",
  "Hampshire and the Isle of Wight", "Hampshire and the Isle of Wight",
  "Healthier Lancashire and South Cumbria", "Healthier Lancashire and South Cumbria",
  "Herefordshire and Worcestershire", "Herefordshire and Worcestershire",
  "Hertfordshire and West Essex", "Hertfordshire and West Essex",
  "Humber, Coast and Vale", "Humber, Coast and Vale",
  "Joined Up Care Derbyshire", "Joined Up Care Derbyshire",
  "Kent and Medway", "Kent and Medway",
  "Leicester, Leicestershire and Rutland", "Leicester, Leicestershire and Rutland",
  "Lincolnshire", "Lincolnshire",
  "Mid and South Essex", "Mid and South Essex",
  "Norfolk and Waveney Health and Care Partnership", "Norfolk and Waveney",
  "North London Partners in Health and Care", "North London",
  "North West London Health and Care Partnership", "North West London",
  "Northamptonshire", "Northamptonshire",
  "Nottingham and Nottinghamshire Health and Care", "Nottingham and Nottinghamshire",
  "Our Healthier South East London", "South East London",
  "Shropshire and Telford and Wrekin", "Shropshire and Telford and Wrekin",
  "Somerset", "Somerset",
  "South West London Health and Care Partnership", "South West London",
  "South Yorkshire and Bassetlaw", "South Yorkshire and Bassetlaw",
  "Staffordshire and Stoke on Trent", "Staffordshire and Stoke on Trent",
  "Suffolk and North East Essex", "Suffolk and North East Essex",
  "Surrey Heartlands Health and Care Partnership", "Surrey Heartlands",
  "Sussex Health and Care Partnership", "Sussex",
  "The Black Country and West Birmingham", "The Black Country and West Birmingham",
  "West Yorkshire and Harrogate (Health and Care Partnership)", "West Yorkshire and Harrogate"
  )

ICB_graph_function <- function(data_input, speciality) {
  
  data <- data_input
  
  function_1 <- function(region){
    data %>% 
      wrangle_function(., stp21nm) %>% 
      left_join(stp_region_lookup, by = c("var_1" = "stp20nm")) %>% 
      mutate(nhser20nm = case_when(str_detect(var_1, "Sussex")~ "South East", TRUE ~ nhser20nm)) %>% 
      filter(nhser20nm == region) %>% 
      filter(!is.nan(prop)) %>% 
      left_join(stp_name_short_lookup, by = c("var_1" = "stp_name")) %>% 
      mutate(stp_name_short = case_when(nchar(stp_name_short) <= 20 ~ stp_name_short, 
                                     TRUE ~ paste0(stringr::str_sub(stp_name_short, 0, 20), "..."))
             ) %>%
      
      ggplot(aes(x = der_activity_month, y = prop, colour = name)) +
      geom_smooth(method = "loess", span = 0.3, se = FALSE) +
      facet_grid(str_wrap(nhser20nm, 12) ~ str_wrap(stp_name_short, 15)) +
      scale_color_SU() +
      scale_y_continuous(limits = c(0,100), oob = squish) +
      scale_x_date(date_breaks = "2 years", labels = label_date_short()) +
      theme(strip.background = element_rect(fill = NA, colour = "grey"),
            strip.text.y = element_text(face = "bold", angle = 0, size = 8), 
            strip.text.x = element_text(size = 7), 
            axis.text.x = element_text(angle = 90),
            legend.position = "none",
            plot.title = element_blank(),
            plot.subtitle = element_blank(),
            axis.title = element_blank())
  }  
  
  plot_1 <- function_1("East of England")
  plot_2 <- function_1("London")
  plot_3 <- function_1("Midlands")
  plot_4 <- function_1("North East and Yorkshire")
  plot_5 <- function_1("North West")
  plot_6 <- function_1("South East")
  plot_7 <- function_1("South West") +
    theme(legend.position = "bottom") + 
    labs(colour = "")
  
  patch_1 <-
    plot_3 +
    (plot_1 + 
       plot_2 +
       plot_4 +
       plot_5 +
       plot_6 +
       plot_7 +
       plot_layout(ncol = 2)) +
    plot_layout(nrow = 2, 
                heights = c(0.2, 0.8)) +    
    plot_annotation(title = "Independent sector provision share by ICB and region", 
                    subtitle = paste0(speciality, " elective care | 2018-22")
                    )
  
  patch_1
  
  }

```

# Regional and Local trends: Orthopaedics

## Region

###   {.tabset}

#### Volume
```{r}
stp_data_ortho %>% 
  wrangle_function(., nhser20nm) %>% 
  filter(!is.nan(prop)) %>% 
  pivot_longer(cols = c(`Independent Sector`, NHS),
               names_to = "sector") %>% 
  ggplot(aes(x = der_activity_month, y = value, colour = var_1)) +
  geom_smooth(method = 'loess', span = 0.4, se = FALSE, size = 1.25) +
  facet_grid(name~sector, scales = "free") +
  scale_color_SU() +
  scale_y_continuous(labels = comma) +
  theme(strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = NA, colour = "grey"),
        axis.title.x = element_blank()
        ) +
  labs(y = "Activity", 
       colour = "NHSE region",
       title = "Regional activity volumes by care type and sector: Orthopaedic",
       subtitle = "Monthly elective activity counts | NHSE region | 2018-22")
```

<div class = "row">
<div class = "col-md-1">
</div>
  
<div class = "col-md-10">

Graph desc... 

</div>

<div class = "col-md-1">
</div>

</div>

#### Independent sector share
```{r}
stp_data_ortho %>% 
  wrangle_function(., nhser20nm) %>% 
  filter(!is.nan(prop)) %>% 
  graph_function(., "Orthopaedic") +
  facet_grid(~str_wrap(var_1,15))
```

<div class = "row">
<div class = "col-md-1">
</div>
  
<div class = "col-md-10">

Graph desc... 

</div>

<div class = "col-md-1">
</div>

</div>

### {.unlisted .unnumbered}

Section desc